// Runs only after installing the actual tarball into an isolated consumer.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { build } from 'esbuild';
import solc from 'solc';
import { Interface, getBytes, getAddress } from 'ethers';
import * as sdk from '@d20dao/vrf-sdk';
import * as epoch from '@d20dao/vrf-sdk/epoch';
import { coordinatorAbi, epochEntropyAbi } from '@d20dao/vrf-sdk/abi';
const iface = new Interface(coordinatorAbi), registry = new Interface(epochEntropyAbi);
assert.deepEqual(coordinatorAbi, JSON.parse(readFileSync('node_modules/@d20dao/vrf-sdk/abi/D20VRFCoordinator.json')));
assert.deepEqual(epochEntropyAbi, JSON.parse(readFileSync('node_modules/@d20dao/vrf-sdk/abi/EpochEntropy.json')));
for (const name of ['requestFee','requestMappedRandomness','refundRequest','retryCallback','getRequest','epochRegistry','retryRefundCallback','refundCallbackDelivered']) assert(iface.getFunction(name));
assert(iface.getEvent('RefundCallbackAttempted'));
for (const name of ['epochStart','epochForBlock','getEpochSelection','getEpoch','commitEpoch']) assert(registry.getFunction(name));
assert(registry.getEvent('EpochCommitted'));
assert(iface.getEvent('FulfillmentEvidence'));
assert.equal(iface.getFunction('fulfillRandomness').inputs.length, 2);
const requestOutputs = JSON.stringify(iface.getFunction('getRequest').outputs);
assert(requestOutputs.includes('epochId') && requestOutputs.includes('epochHash'));
assert(!requestOutputs.includes('apiDataHash'));
const fixtureProvenance = JSON.parse(readFileSync('fixture-provenance.json','utf8'));
assert(['live API3','explicit CI fixture'].includes(fixtureProvenance.sourceMode));
const fixtures = JSON.parse(readFileSync('fixture-names.json','utf8')).map(name => JSON.parse(readFileSync(name,'utf8'), (_key,value) => typeof value === 'string' && /^[0-9]+$/.test(value) ? BigInt(value) : value));
const fixture = fixtures[0];
const canonicalProof = proof => ({...proof,uWitness:getAddress(proof.uWitness)});
const coveredSources = [...new Set(fixtures.map(f => Number(f.epoch.record.source)))].sort();
assert.deepEqual(coveredSources,[0,1,2,3], 'Current fixture coverage must include all four recipe slots');
assert.equal(registry.deploy.inputs.length,0);
assert.equal(iface.deploy.inputs.length,0);
assert.equal(registry.getFunction('initialize').inputs[0].type,'address[4]');
for (const abi of [iface,registry]) for (const name of ['initialize','owner','pendingOwner','upgradeToAndCall']) assert(abi.getFunction(name));
assert(iface.getFunction('initialFeeRecipient'));
assert(requestOutputs.includes('requestBlock') && requestOutputs.includes('targetBlock'));
assert(fixtures.some(f => epoch.epochForBlock(f.configuration.firstEpochStart,f.acceptanceBlock) > f.context.epochId), 'Fixture set must replay a request accepted across an epoch boundary');
for (const f of fixtures) {
 assert.equal(f.epoch.catalog.signers.length,4);
 const evidence = epoch.decodeEpochEvidencePacket(f.epoch.packet);
 assert(getBytes(evidence.attestation.data).length <= 128);
 const replayed = sdk.replayCoordinator(f);
 assert.equal(replayed.reveal.randomness,f.recorded.randomness);
 assert.equal(sdk.deriveRequestSeed(f.context),f.vrfProof.seed);
 assert.deepEqual(sdk.decodeEvidencePacket(sdk.encodeEvidencePacket(f.vrfProof)).proof,canonicalProof(f.vrfProof));
}
const result = sdk.replayCoordinator(fixture);
assert.equal(result.reveal.randomness, fixture.recorded.randomness);
assert.equal(sdk.deriveRequestSeed(fixture.context), fixture.vrfProof.seed);
assert.equal(sdk.epochProtocolConfigurationHash(fixture.configuration), fixture.protocolConfigurationHash);
const packet = sdk.encodeEvidencePacket(fixture.vrfProof);
assert.equal(getBytes(packet).length, 416);
assert.equal(getBytes(iface.encodeFunctionData('fulfillRandomness',[fixture.context.requestId,fixture.vrfProof])).length,452);
assert.deepEqual(sdk.decodeEvidencePacket(packet).proof, canonicalProof(fixture.vrfProof));
assert.throws(() => sdk.decodeEvidencePacket(packet + '00'));
assert.throws(() => sdk.decodeEvidencePacket(packet.slice(0,-2)));
assert.throws(() => sdk.decodeEvidencePacket(fixture.epoch.packet));
assert.throws(() => epoch.decodeEpochEvidencePacket(packet));
const decodedEpoch = epoch.decodeEpochEvidencePacket(fixture.epoch.packet);
assert.equal(epoch.encodeEpochEvidencePacket(decodedEpoch.canonicalRequest,decodedEpoch.attestation),fixture.epoch.packet);
assert.throws(() => epoch.decodeEpochEvidencePacket(fixture.epoch.packet+'00'));
assert.throws(() => sdk.replayCoordinator({...fixture,context:{...fixture.context,epochId:fixture.context.epochId+1n}}));
assert.throws(() => sdk.replayCoordinator({...fixture,context:{...fixture.context,epochHash:'0x'+'00'.repeat(32)}}));
assert.throws(() => sdk.replayCoordinator({...fixture,context:{...fixture.context,requestBlock:fixture.context.requestBlock+1n}}));
assert.throws(() => sdk.replayCoordinator({...fixture,context:{...fixture.context,targetBlock:fixture.context.targetBlock-1n}}));
assert.throws(() => sdk.replayCoordinator({...fixture,vrfProof:{...fixture.vrfProof,seed:0n}}));
assert.throws(() => sdk.replayCoordinator({...fixture,acceptanceTimestamp:fixture.deadline+1n}));
assert.throws(() => sdk.replayCoordinator({...fixture,epoch:{...fixture.epoch,record:{...fixture.epoch.record,committedBlock:fixture.context.targetBlock}}}));
assert.equal(epoch.epochForBlock(300n,299n),0n);
assert.equal(epoch.epochForBlock(300n,300n),1n);
assert.equal(epoch.epochForBlock(300n,499n),1n);
assert.equal(epoch.epochForBlock(300n,500n),2n);
assert([0,1,2,3].includes(Number(fixture.epoch.record.source)));
const mapped = sdk.mapRandomness(result.reveal.randomness,sdk.builtins.d20());
assert(mapped.length===1 && mapped[0]>=1n && mapped[0]<=20n);
const bundle = await build({stdin:{contents:"export * from '@d20dao/vrf-sdk'; export * from '@d20dao/vrf-sdk/abi';",resolveDir:process.cwd(),sourcefile:'public-entry.js'},bundle:true,platform:'browser',format:'esm',target:'es2022',write:false,metafile:true});
const forbidden = Object.keys(bundle.metafile.inputs).filter(p=>/(^|\/)(keeper|test|secrets)(\/|$)|node:/.test(p.replaceAll('\\','/')));
assert.deepEqual(forbidden,[]);
const browser = await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
for (const f of fixtures) assert.deepEqual(browser.replayCoordinator(f),sdk.replayCoordinator(f));
assert.deepEqual(browser.coordinatorAbi,coordinatorAbi);
assert.deepEqual(browser.epochEntropyAbi,epochEntropyAbi);
assert.deepEqual(browser.decodeEvidencePacket(packet).proof,canonicalProof(fixture.vrfProof));
const input={language:'Solidity',sources:{'DiceConsumer.sol':{content:readFileSync('DiceConsumer.sol','utf8')},'MiningImport.sol':{content:'pragma solidity 0.8.28; import "@d20dao/vrf-sdk/contracts/examples/MiningRandomnessConsumer.sol";'}},settings:{optimizer:{enabled:true,runs:200},evmVersion:'cancun',outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}};
const compiled=JSON.parse(solc.compile(JSON.stringify(input),{import:p=>{try{if(!p.startsWith('@d20dao/vrf-sdk/')||p.includes('..'))throw new Error('unexpected import');return {contents:readFileSync(resolve('node_modules',p),'utf8')};}catch(e){return {error:e.message};}}}));
assert.deepEqual((compiled.errors??[]).filter(e=>e.severity==='error'),[]);
assert(compiled.contracts['DiceConsumer.sol'].DiceConsumer.evm.bytecode.object.length>0);
const consumer=new Interface(compiled.contracts['@d20dao/vrf-sdk/contracts/interfaces/ID20VRF.sol'].ID20VRF.abi);
consumer.forEachFunction(fragment=>{
 const coordinator=iface.getFunction(fragment.format('sighash'));assert(coordinator);
 assert.equal(coordinator.selector,fragment.selector);assert.equal(coordinator.stateMutability,fragment.stateMutability);
 assert.deepEqual(coordinator.outputs.map(p=>p.format('sighash')),fragment.outputs.map(p=>p.format('sighash')));
});
console.log(fixtureProvenance.sourceMode+' recipe fixture coverage: '+coveredSources.join(', '));
console.log('Current epoch/VRF replay, ABI, strict TypeScript, browser-target bundle ('+bundle.outputFiles[0].contents.length+' bytes) and Solidity checks passed.');
